CREATE TABLE students(
  id int NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT 'Primary Key',
  std_name VARCHAR(255) COMMENT '',
  std_age VARCHAR(255) COMMENT '',
  std_country VARCHAR(255) COMMENT ''
) DEFAULT CHARSET UTF8 COMMENT '';